import type {Lang, TranslationKey} from './i18n/index'
import {t, poiName, nodeName} from './i18n/index'
export type Vec3 = [number,number,number]
export type Category='ritual'|'gate'|'water'|'toilet'|'medical'|'cart'|'elevator'|'escalator'|'meeting'|'accessible'
export type NavNode={id:string;position:Vec3;floor:number;name:string}
export type Edge={id:string;from:string;to:string;distance:number;kind:'walk'|'stairs'|'elevator'|'escalator'|'ramp';accessible:boolean}
export type POI={id:string;name:string;description:string;category:Category;nodeId:string;position:Vec3;floor:number;symbol:string;color:string}
export const floors=[{id:0,name:'الدور الأرضي',short:'G',y:0},{id:1,name:'الدور الأول',short:'1',y:9},{id:2,name:'السطح',short:'2',y:18},{id:3,name:'مستوى المسعى',short:'M',y:4.5}]
export const categories:{id:Category;name:string;symbol:string;color:string}[]=[{id:'ritual',name:'المناسك',symbol:'◇',color:'#a68b53'},{id:'gate',name:'الأبواب',symbol:'↥',color:'#586f61'},{id:'water',name:'زمزم',symbol:'♧',color:'#4a91a2'},{id:'toilet',name:'دورات المياه',symbol:'WC',color:'#708e99'},{id:'medical',name:'الإسعافات',symbol:'+',color:'#b7786b'},{id:'cart',name:'العربات',symbol:'♿',color:'#7b7eab'},{id:'elevator',name:'المصاعد',symbol:'↕',color:'#778e75'},{id:'escalator',name:'السلالم الكهربائية',symbol:'↗',color:'#6d8f7e'},{id:'meeting',name:'نقاط اللقاء',symbol:'◎',color:'#b18b65'},{id:'accessible',name:'ذوو الإعاقة',symbol:'♿',color:'#8289a7'}]
export const distance=(a:Vec3,b:Vec3)=>Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2])
export const nodes:NavNode[]=[];export const edges:Edge[]=[]
function node(id:string,position:Vec3,floor:number,name:string){nodes.push({id,position,floor,name});return id}
function edge(from:string,to:string,kind:Edge['kind']='walk',accessible=true,id=`${from}:${to}`){edges.push({id,from,to,kind,accessible,distance:distance(nodes.find(n=>n.id===from)!.position,nodes.find(n=>n.id===to)!.position)*2.8})}
for(let f=0;f<3;f++){
 for(let i=0;i<16;i++){const a=i/16*Math.PI*2;node(`f${f}-r${i}`,[Math.cos(a)*32,f*9,Math.sin(a)*32],f,'رواق المطاف')}
 for(let i=0;i<16;i++)edge(`f${f}-r${i}`,`f${f}-r${(i+1)%16}`)
 for(const [id,p,ring] of [['east',[48,f*9,22],1],['north',[0,f*9,-54],12],['south',[0,f*9,54],4],['lift',[-48,f*9,15],7],['stairs',[48,f*9,14],0],['escalator',[48,f*9,-17],15]] as [string,Vec3,number][]){node(`f${f}-${id}`,p,f,id==='lift'?'المصعد الغربي':id==='stairs'?'السلالم الشرقية':id==='escalator'?'السلم الكهربائي':'الرواق');edge(`f${f}-${id}`,`f${f}-r${ring}`)}
 if(f>0){edge(`f${f-1}-lift`,`f${f}-lift`,'elevator');edge(`f${f-1}-stairs`,`f${f}-stairs`,'stairs',false);edge(`f${f-1}-escalator`,`f${f}-escalator`,'escalator',false)}
}
node('passage',[58,2.5,44],0,'الممر إلى المسعى');node('safa',[71,4.5,65],3,'الصفا');node('marwa',[71,4.5,-65],3,'المروة');node('masaa-middle',[71,4.5,0],3,'المسعى');node('north-passage',[58,2.5,-44],0,'الممر الشمالي')
edge('f0-east','passage','ramp',true,'main-passage');edge('passage','safa','ramp');edge('safa','masaa-middle');edge('masaa-middle','marwa');edge('f0-escalator','north-passage','ramp');edge('north-passage','marwa','ramp');node('prayer-behind-maqam',[26,0,9.3],0,'خلف مقام إبراهيم');edge('f0-r0','prayer-behind-maqam');edge('f0-r1','prayer-behind-maqam')
const poi=(id:string,name:string,category:Category,nodeId:string,description:string,offset?:Vec3):POI=>{const n=nodes.find(n=>n.id===nodeId)!;const c=categories.find(c=>c.id===category)!;return{id,name,category,nodeId,description,position:offset||n.position,floor:n.floor,symbol:c.symbol,color:c.color}}
export const pois:POI[]=[
 poi('kaaba','الكعبة المشرفة','ritual','f0-r8','في قلب صحن المطاف؛ التوجيه إلى المنطقة المحيطة بها.',[0,10,0]),
 poi('mataf','صحن المطاف','ritual','f0-r2','منطقة الطواف حول الكعبة المشرفة.'),poi('tawaf-start','بداية الطواف','ritual','f0-r0','نقطة بدء المسار التجريبي للطواف.'),poi('prayer','ركعتا الطواف · خلف المقام','ritual','prayer-behind-maqam','موضع تجريبي خلف مقام إبراهيم للصلاة عند التيسّر.'),poi('maqam','مقام إبراهيم','ritual','prayer-behind-maqam','معلم بصري؛ منطقة الصلاة خلف المقام.',[14,2,5]),
 poi('safa','الصفا','ritual','safa','بداية السعي؛ الشوط الأول باتجاه المروة.'),poi('marwa','المروة','ritual','marwa','نهاية الشوط الأول والسابع من السعي.'),
 poi('gate-fahd','باب الملك فهد','gate','f0-south','مدخل رئيسي تجريبي إلى الأروقة والمطاف.'),poi('exit','باب المروة · مخرج','gate','f0-north','المخرج المقترح بعد إكمال السعي.'),poi('mataf-exit','مخرج المطاف','gate','f0-east','نقطة انطلاق سيناريو الهاكثون.'),
 poi('zamzam','ماء زمزم','water','f0-r13','نقطة مياه تجريبية قريبة من المطاف.'),poi('zamzam-upper','زمزم · الأول','water','f1-r10','نقطة مياه في الدور الأول.'),poi('toilet','دورات المياه','toilet','f0-lift','خدمة تجريبية عند الرواق الغربي.'),poi('medical','الإسعافات الأولية','medical','f0-r6','نقطة إسعافات تجريبية.'),poi('cart','مركز العربات','cart','f0-r5','نقطة تجريبية لخدمة العربات.'),poi('family','ملتقى العائلة','meeting','f0-r9','نقطة واضحة للاجتماع مع العائلة.'),
 ...[0,1,2].flatMap(f=>[poi(`lift-${f}`,'المصعد الغربي','elevator',`f${f}-lift`,'يربط الأرضي والأول والسطح، ومناسب للكرسي المتحرك.'),poi(`escalator-${f}`,'السلم الكهربائي','escalator',`f${f}-escalator`,'اتصال تجريبي بين مستويات الرواق.'),poi(`accessible-${f}`,'مصلى ذوي الإعاقة','accessible',`f${f}-r11`,'موقع تجريبي يمكن الوصول إليه عبر المصعد.')]),poi('roof','مصلى السطح','ritual','f2-r3','منطقة صلاة في المستوى العلوي التجريبي.'),poi('upper-prayer','مصلى الدور الأول','ritual','f1-r3','منطقة صلاة في الدور الأول.'),poi('masaa-water','زمزم · المسعى','water','masaa-middle','نقطة تجريبية في منتصف المسعى.')]
export const stages=[{name:'الدخول إلى المسجد الحرام',poi:'gate-fahd',hint:'ابدأ رحلتك من الباب الرئيسي'},{name:'التوجه إلى المطاف',poi:'mataf',hint:'اتبع المسار إلى صحن المطاف'},{name:'الوصول إلى بداية الطواف',poi:'tawaf-start',hint:'توجّه إلى نقطة بداية الطواف'},{name:'الطواف سبعة أشواط',poi:'tawaf-start',hint:'أكد إكمال كل شوط بنفسك'},{name:'ركعتا الطواف خلف المقام',poi:'prayer',hint:'المقام أمامك والكعبة خلفه · صلّ ركعتين عند التيسّر'},{name:'ماء زمزم',poi:'zamzam',hint:'موقع زمزم القريب من المطاف'},{name:'التوجه إلى الصفا',poi:'safa',hint:'بداية مسارك إلى المسعى'},{name:'السعي سبعة أشواط',poi:'safa',hint:'من الصفا إلى المروة، ثم العودة'},{name:'الخروج للحلق أو التقصير',poi:'exit',hint:'توجه إلى المخرج لإتمام النسك'},{name:'اكتمال رحلة العمرة',poi:'exit',hint:'أكد إتمام رحلتك'}]
export function nearestNode(p:Vec3,floor:number){return nodes.filter(n=>n.floor===floor).sort((a,b)=>distance(a.position,p)-distance(b.position,p))[0]}
export function shortestPath(from:string,to:string,accessible=false,closed:string[]=[],preferQuiet=false):{ids:string[];points:Vec3[];meters:number}|null{
 if(!nodes.some(n=>n.id===from)||!nodes.some(n=>n.id===to))return null
 const costs=new Map<string,number>([[from,0]]),previous=new Map<string,string>(),pending=new Set(nodes.map(n=>n.id))
 while(pending.size){const current=[...pending].sort((a,b)=>(costs.get(a)??Infinity)-(costs.get(b)??Infinity))[0];if(!Number.isFinite(costs.get(current)))break;pending.delete(current);if(current===to)break
 for(const e of edges){if(closed.includes(e.id)||(accessible&&!e.accessible))continue;const next=e.from===current?e.to:e.to===current?e.from:null;if(!next||!pending.has(next))continue;const c=costs.get(current)!+e.distance*(preferQuiet?1+crowdLevel(e)*18:1);if(c<(costs.get(next)??Infinity)){costs.set(next,c);previous.set(next,current)}}}
 if(!costs.has(to))return null;const ids=[to];while(ids[0]!==from){const prev=previous.get(ids[0]);if(!prev)return null;ids.unshift(prev)}return{ids,points:ids.map(id=>nodes.find(n=>n.id===id)!.position),meters:ids.slice(1).reduce((sum,id,i)=>sum+distance(nodes.find(n=>n.id===ids[i])!.position,nodes.find(n=>n.id===id)!.position)*2.8,0)}
}
export function pathLength(points:Vec3[]){return points.slice(1).reduce((sum,p,i)=>sum+distance(points[i],p),0)}
export function pointAlong(points:Vec3[],progress:number):{position:Vec3;direction:number}{if(points.length<2)return{position:points[0]||[0,0,0],direction:0};let remaining=Math.max(0,Math.min(1,progress))*pathLength(points);for(let i=1;i<points.length;i++){const d=distance(points[i-1],points[i]);if(remaining<=d||i===points.length-1){const t=d?Math.min(1,remaining/d):1,a=points[i-1],b=points[i];return{position:[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t],direction:Math.atan2(-(b[0]-a[0]),-(b[2]-a[2]))}}remaining-=d}return{position:points.at(-1)!,direction:0}}
export function remainingPath(points:Vec3[],progress:number):Vec3[]{if(points.length<2)return points;let passed=0,total=pathLength(points);for(let i=1;i<points.length;i++){passed+=distance(points[i-1],points[i]);if(passed>=progress*total)return[pointAlong(points,progress).position,...points.slice(i)]}return[points.at(-1)!]}
export function tawafPath():Vec3[]{return Array.from({length:81},(_,i)=>{const a=-i/80*Math.PI*2;return[Math.cos(a)*23,0,Math.sin(a)*23]})}

/** Static demo occupancy, never live crowd data. */
export function crowdLevel(edge:Edge){return edge.id==='main-passage'||edge.from==='passage'||edge.to==='passage'?.92:edge.kind==='stairs'?.45:.04}
export type NavigationStep={index:number;position:Vec3;meters:number;instruction:string;landmark:string;floor:number;kind:Edge['kind'];turn:'forward'|'right'|'left'|'arrive'|'vertical'}
export function navigationSteps(route:Vec3[],ids:string[],destinationName:string,lang:Lang='ar'):NavigationStep[]{
 return route.slice(1).map((end,i)=>{const start=route[i],node=nodes.find(n=>distance(n.position,end)<.01),prev=route[Math.max(0,i-1)];const a=[start[0]-prev[0],start[2]-prev[2]],b=[end[0]-start[0],end[2]-start[2]];const cross=a[0]*b[1]-a[1]*b[0];const angle=Math.atan2(cross,a[0]*b[0]+a[1]*b[1])*180/Math.PI;const idIndex=node?ids.indexOf(node.id):-1;const edge=edges.find(e=>idIndex>0&&(e.from===ids[idIndex-1]&&e.to===node!.id||e.to===ids[idIndex-1]&&e.from===node!.id));const kind=edge?.kind||'walk';const vertical=['stairs','elevator','escalator'].includes(kind);const turn:NavigationStep['turn']=vertical?'vertical':i===0||Math.abs(angle)<25?'forward':angle>0?'right':'left';const landmarkKey:TranslationKey|null=node?.id==='safa'?'landmark.safa':node?.id==='marwa'?'landmark.marwa':node?.id==='passage'?'landmark.passage':node?.id==='north-passage'?'landmark.north-passage':node?.id==='prayer-behind-maqam'?'landmark.prayer-behind-maqam':node?.id==='f0-south'?'landmark.f0-south':node?.id.includes('lift')?'landmark.lift':null;const landmark=landmarkKey?t(landmarkKey,lang):node?nodeName(node.name,lang):destinationName;return{index:i,position:start,meters:Math.round(distance(start,end)*2.8),instruction:vertical?kind==='elevator'?t('nav.use_elevator',lang):kind==='stairs'?t('nav.use_stairs',lang):t('nav.use_escalator',lang):turn==='right'?t('nav.turn_right',lang):turn==='left'?t('nav.turn_left',lang):t('nav.turn_forward',lang),landmark,floor:node?.floor||0,kind,turn}})
}
export function activeStepIndex(route:Vec3[],progress:number){let sum=0;const total=pathLength(route);for(let i=1;i<route.length;i++){sum+=distance(route[i-1],route[i]);if(sum>=progress*total+.01)return i-1}return Math.max(0,route.length-2)}
// The Arabic keyword shortcuts below (خلصت طواف/اقرب مخرج/مسعى/صفا/مروة/
// زمزم) are intentionally Arabic-only - they stay exactly as before.
// `lang` only extends the generic POI-name matching (last resort before
// returning {}) to also check the localized name for the current
// language, via i18n/poi.ts::poiName - free-form questions in any
// language belong to Siraj (src/siraj.ts), not this function.
export function resolveDestination(query:string,lang:Lang='ar'):{id?:string;nearest?:Category}{const q=query.replace(/[أإآ]/g,'ا').replace(/[؟?!.]/g,'').trim();if(q.includes('خلصت طواف')||q.includes('خلص طواف')||q.includes('انتهيت من الطواف'))return{id:'prayer'};if(q.includes('اقرب')&&q.includes('مخرج'))return{nearest:'gate'};if(q.includes('مسعى')||q.includes('المسعي')||q.includes('صفا'))return{id:'safa'};if(q.includes('مروة'))return{id:'marwa'};if(q.includes('زمزم'))return{nearest:'water'};const found=pois.find(p=>q.includes(p.name.replace(/[أإآ]/g,'ا')));if(found)return{id:found.id};if(lang!=='ar'){const nq=query.replace(/[؟?!.]/g,'').trim().toLowerCase();if(nq){const localized=pois.find(p=>{const name=poiName(p.id,lang).toLowerCase();return name&&(nq.includes(name)||name.includes(nq))});if(localized)return{id:localized.id}}}return{}}
