import test from 'node:test'
import assert from 'node:assert/strict'
import {edges,nodes,pois,shortestPath,distance,pathLength,pointAlong,tawafPath,remainingPath} from './navigation'
import {MockLocationProvider} from './location'

test('all POIs resolve and graph is connected on every floor',()=>{for(const p of pois){assert.ok(nodes.some(n=>n.id===p.nodeId));assert.ok(shortestPath('f0-south',p.nodeId),p.id)}})
test('all POIs have an accessible route without stairs or escalators',()=>{for(const p of pois){const r=shortestPath('f0-south',p.nodeId,true)!;assert.ok(r,p.id);for(let i=1;i<r.ids.length;i++){const e=edges.find(e=>e.from===r.ids[i-1]&&e.to===r.ids[i]||e.to===r.ids[i-1]&&e.from===r.ids[i])!;assert.ok(e.accessible,p.id)}}})
test('closing eastern corridor produces a longer route via north passage',()=>{const a=shortestPath('f0-east','safa')!,b=shortestPath('f0-east','safa',false,['main-passage'])!;assert.ok(a.ids.includes('passage'));assert.ok(!b.ids.includes('passage'));assert.ok(b.ids.includes('north-passage'));assert.ok(b.meters>a.meters)})
test('cross-floor wheelchair path uses elevator with vertical coordinates',()=>{const r=shortestPath('f0-stairs','f2-stairs',true)!;assert.ok(r.ids.includes('f1-lift'));assert.equal(r.points.at(-1)![1],18)})
test('unreachable and invalid destinations return null',()=>{assert.equal(shortestPath('missing','safa'),null);assert.equal(shortestPath('f0-east','safa',false,edges.map(e=>e.id)),null)})
test('distance is sum of edge lengths and same node costs zero',()=>{const r=shortestPath('f0-east','safa')!;assert.ok(Math.abs(r.meters-pathLength(r.points)*2.8)<1e-8);assert.equal(shortestPath('safa','safa')!.meters,0)})
test('mock provider moves continuously and reaches exact endpoint',()=>{const p=new MockLocationProvider(),route=shortestPath('f0-east','safa')!.points;let progress=0,previous=route[0];for(let i=0;i<200;i++){const s=p.advance(route,progress,.1,5);assert.ok(distance(s.position,previous)<=.50001);progress=s.progress;previous=s.position}assert.equal(progress,1);assert.deepEqual(previous,route.at(-1))})
test('remaining route begins at interpolated current position after resume',()=>{const route=shortestPath('f0-east','safa')!.points;const p=pointAlong(route,.5).position;const remaining=remainingPath(route,.5);assert.deepEqual(remaining[0],p);assert.deepEqual(remaining.at(-1),route.at(-1));assert.ok(Math.abs(pathLength(remaining)-pathLength(route)/2)<1e-8)})
test('tawaf path closes and never passes through Kaaba',()=>{const path=tawafPath();assert.ok(distance(path[0],path.at(-1)!)<1e-10);assert.ok(path.every(p=>Math.hypot(p[0],p[2])>22.9))})
const memory=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{value:{getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>memory.set(k,v),removeItem:(k:string)=>memory.delete(k)},configurable:true})
const {useMap,STORAGE_KEY}=await import('./store')
const initial=useMap.getInitialState()
function reset(){memory.clear();useMap.setState({...initial},true)}
test('demo saves mid-route and hydration resumes exact coordinates',async()=>{reset();useMap.getState().startDemo();for(let i=0;i<200&&useMap.getState().running;i++)useMap.getState().tick(.1);const paused=useMap.getState();assert.equal(paused.demo,'saved');assert.equal(paused.paused,true);assert.ok(paused.progress>=.5&&paused.progress<.6);assert.ok(paused.stoppedAt);const saved=memory.get(STORAGE_KEY)!;const pos=[...paused.position];const progress=paused.progress;useMap.setState({...initial},true);memory.set(STORAGE_KEY,saved);await useMap.persist.rehydrate();assert.deepEqual(useMap.getState().position,pos);assert.equal(useMap.getState().progress,progress);assert.equal(useMap.getState().running,false);useMap.getState().resume();assert.equal(useMap.getState().demo,'resumed');for(let i=0;i<200&&useMap.getState().running;i++)useMap.getState().tick(.1);assert.equal(useMap.getState().demo,'arrived');assert.equal(useMap.getState().stage,6);assert.equal(useMap.getState().confirmArrival('safa'),true);assert.equal(useMap.getState().ritual,'sai');assert.equal(useMap.getState().stage,7)})
test('arrival cannot complete ritual automatically or confirm from another floor',()=>{reset();assert.equal(useMap.getState().confirmArrival('safa'),false);useMap.getState().completeStage();assert.equal(useMap.getState().stage,0);useMap.getState().confirmArrival('gate-fahd');useMap.getState().completeStage();assert.equal(useMap.getState().stage,1)})
test('seven sai legs alternate with seventh ending at Marwa, then suggest exit',()=>{reset();useMap.getState().startRitual('sai');for(let i=0;i<7;i++){const s=useMap.getState();assert.equal(s.route[0][2],i%2===0?65:-65);assert.equal(s.route.at(-1)![2],i%2===0?-65:65);s.completeLap()}assert.equal(useMap.getState().sai,7);assert.equal(useMap.getState().destination,'exit');assert.equal(useMap.getState().stage,8)})
test('tawaf undo and seven manual confirmations advance to prayer',()=>{reset();useMap.getState().startRitual('tawaf');useMap.getState().completeLap();assert.equal(useMap.getState().tawaf,1);useMap.getState().undoLap();assert.equal(useMap.getState().tawaf,0);for(let i=0;i<7;i++)useMap.getState().completeLap();assert.equal(useMap.getState().tawaf,7);assert.equal(useMap.getState().destination,'prayer');assert.equal(useMap.getState().stage,4)})
test('floor selection preserves location and route; simulated relocation recalculates',()=>{reset();useMap.getState().navigate('safa');const before=useMap.getState();useMap.getState().setFloor(2);assert.deepEqual(useMap.getState().position,before.position);assert.deepEqual(useMap.getState().route,before.route);useMap.getState().moveTo([0,0,-54],0);assert.equal(useMap.getState().routeIds[0],'f0-north');assert.equal(useMap.getState().destination,'safa')})

test('quiet route avoids simulated dense passage and reports actual length',async()=>{const {crowdLevel}=await import('./navigation');const fast=shortestPath('f0-east','safa')!,quiet=shortestPath('f0-east','safa',false,[],true)!;assert.ok(fast.ids.includes('passage'));assert.ok(!quiet.ids.includes('passage'));assert.ok(quiet.meters>fast.meters);assert.ok(Math.abs(quiet.meters-pathLength(quiet.points)*2.8)<1e-8);assert.ok(crowdLevel(edges.find(e=>e.id==='main-passage')!)>.8)})
test('manual completed-tawaf status navigates behind Maqam then next stages',()=>{reset();useMap.getState().finishTawaf();assert.equal(useMap.getState().tawaf,7);assert.equal(useMap.getState().stage,4);assert.equal(useMap.getState().destination,'prayer');assert.equal(useMap.getState().follow,true);for(let i=0;i<200&&useMap.getState().running;i++)useMap.getState().tick(.1);assert.deepEqual(useMap.getState().position,[26,0,9.3]);assert.equal(useMap.getState().stage,4);useMap.getState().confirmArrival('prayer');useMap.getState().completeStage();assert.equal(useMap.getState().stage,5);assert.equal(useMap.getState().destination,'zamzam')})
test('lost mode preserves journey and picks a reachable known landmark',()=>{reset();const pos=useMap.getState().position;useMap.getState().lost();assert.ok(useMap.getState().lostLandmark);assert.deepEqual(useMap.getState().position,pos);assert.equal(useMap.getState().stage,0)})
test('query shortcuts and navigation steps are data driven',async()=>{const {resolveDestination,navigationSteps}=await import('./navigation');assert.equal(resolveDestination('أبغى أروح للمسعى').id,'safa');assert.equal(resolveDestination('وين الصفا؟').id,'safa');assert.equal(resolveDestination('أقرب مخرج؟').nearest,'gate');const route=shortestPath('f0-east','safa')!;const steps=navigationSteps(route.points,route.ids,'الصفا');assert.equal(steps.length,2);assert.match(steps[1].landmark,/الصفا/);assert.ok(steps.every(s=>s.meters>0))})
