import test from 'node:test'
import assert from 'node:assert/strict'
import {pois,nodes,edges,shortestPath,distance,navigationSteps,resolveDestination} from './navigation'
import {regions,regionalPOINames,regionalText,regionNames,regionAt} from './geography'
import {poiName,nodeName} from './i18n/index'
import {SIRAJ_TO_SAKINA_POI} from './siraj'
const memory=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{value:{getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>memory.set(k,v),removeItem:(k:string)=>memory.delete(k)},configurable:true})
const {useMap,STORAGE_KEY}=await import('./store');const initial=useMap.getInitialState();const reset=()=>{memory.clear();useMap.setState({...initial},true)}
test('all regions have valid entry nodes and reachable primary destinations',()=>{for(const r of regions){const n=nodes.find(n=>n.id===r.entry)!;assert.ok(n);assert.equal(n.region,r.id);assert.ok(shortestPath(r.entry,pois.find(p=>p.id===r.destination)!.nodeId,true))}})
test('all regional ids are unique and POIs resolve in seven languages',()=>{assert.equal(new Set(nodes.map(n=>n.id)).size,nodes.length);assert.equal(new Set(pois.map(p=>p.id)).size,pois.length);for(const id of Object.keys(regionalPOINames))for(const lang of ['ar','en','ur','id','tr','fr','fa'] as const){assert.notEqual(poiName(id,lang),id);assert.ok(pois.some(p=>p.id===id))}for(const table of [regionalText,regionNames])for(const entry of Object.values(table))assert.equal(Object.keys(entry).length,7)})
test('Mina wheelchair route uses elevator to upper Jamarat level',()=>{const r=shortestPath('mina-camp','jamrah-middle-2',true)!;assert.ok(r.ids.includes('mina-lift-1'));assert.ok(r.ids.includes('mina-lift-2'));assert.equal(r.points.at(-1)![1],18);for(let i=1;i<r.ids.length;i++){const e=edges.find(e=>e.from===r.ids[i-1]&&e.to===r.ids[i]||e.to===r.ids[i-1]&&e.from===r.ids[i])!;assert.ok(e.accessible)}})
test('Mina and Arafat closures have actual alternate paths',()=>{for(const [from,to,closed] of [['mina-camp','mina-middle','mina-main-passage'],['arafat-center','jabal-rahmah','arafat-main-passage']]){const a=shortestPath(from,to)!,b=shortestPath(from,to,false,[closed])!;assert.ok(b);assert.ok(b.meters>a.meters);assert.notDeepEqual(a.ids,b.ids)}})
test('quiet route avoids the simulated crowded Arafat passage',()=>{const a=shortestPath('arafat-center','jabal-rahmah')!,b=shortestPath('arafat-center','jabal-rahmah',false,[],true)!;assert.ok(a.ids.includes('arafat-site'));assert.ok(!b.ids.includes('arafat-site'))})
test('between-sites route passes Mina and Muzdalifah and supports directions',()=>{const r=shortestPath('f0-south','jabal-rahmah',true)!;assert.ok(r.ids.includes('mina-entry'));assert.ok(r.ids.includes('muz-entry'));assert.ok(r.ids.includes('arafat-entry'));assert.equal(navigationSteps(r.points,r.ids,'عرفات').length,r.points.length-1)})
test('viewing regions and floors preserves current location and Umrah progress',()=>{reset();useMap.setState({tawaf:3,stage:3});const p=[...useMap.getState().position];useMap.getState().setRegion('mina');useMap.getState().setFloor(2);assert.equal(useMap.getState().region,'mina');assert.equal(useMap.getState().floor,2);assert.deepEqual(useMap.getState().position,p);assert.equal(useMap.getState().tawaf,3);assert.equal(useMap.getState().stage,3)})
test('explicit regional simulation moves to that entry and completes the route',()=>{for(const region of ['mina','arafat','towers'] as const){reset();useMap.getState().startRegionDemo(region);assert.equal(useMap.getState().running,true);assert.equal(useMap.getState().region,region);for(let i=0;i<1000&&useMap.getState().running;i++)useMap.getState().tick(.1);const s=useMap.getState(),p=pois.find(p=>p.id===s.destination)!;assert.ok(distance(s.position,nodes.find(n=>n.id===p.nodeId)!.position)<.001);assert.equal(s.confirmArrival(p.id),true)}})
test('regional pause/hydration preserves exact coordinates and destination',async()=>{reset();useMap.getState().startRegionDemo('arafat');for(let i=0;i<20;i++)useMap.getState().tick(.1);useMap.getState().pause();const before=useMap.getState(),saved=memory.get(STORAGE_KEY)!;useMap.setState({...initial},true);memory.set(STORAGE_KEY,saved);await useMap.persist.rehydrate();const after=useMap.getState();assert.deepEqual(after.position,before.position);assert.equal(after.region,'arafat');assert.equal(after.destination,before.destination);assert.equal(after.progress,before.progress);assert.equal(after.running,false)})
test('new place search and Siraj clock tower mapping resolve',()=>{assert.equal(resolveDestination('جبل الرحمة').id,'jabal-rahmah');assert.equal(resolveDestination('Namirah Mosque','en').id,'namirah');assert.equal(SIRAJ_TO_SAKINA_POI['MCH-LMK-003'],'clock-tower')})
test('regional intermediate landmarks and current location are localized',()=>{const route=shortestPath('mina-entry','mina-camp')!;const steps=navigationSteps(route.points,route.ids,'Pilgrim Camp','en');assert.ok(steps.some(s=>s.landmark==='Mina'));assert.ok(steps.every(s=>!/[\u0600-\u06ff]/.test(s.landmark)));assert.equal(nodeName('منى','en'),'Mina');assert.equal(nodeName('مسجد نمرة','en'),'Namirah Mosque')})
test('browsing a different floor while walking preserves the viewed floor',()=>{reset();useMap.getState().navigate('safa');useMap.getState().simulate();useMap.getState().setFloor(8);const before=useMap.getState().position;useMap.getState().tick(.1);const s=useMap.getState();assert.equal(s.floor,8);assert.equal(s.follow,false);assert.notDeepEqual(s.position,before);assert.equal(s.userFloor,0)})
test('legacy journey migration moves the remaining route onto repaired upper decks and preserves counters',async()=>{reset();memory.set(STORAGE_KEY,JSON.stringify({version:1,state:{position:[32,9,0],userFloor:1,floor:1,region:'haram',nodeId:'f1-r0',destination:'upper-prayer',route:[[32,9,0],[0,9,32]],routeIds:['f1-r0','f1-r4'],progress:.4,stage:4,tawaf:7,sai:2,completed:[0,1,2,3],accessible:true}}));await useMap.persist.rehydrate();const s=useMap.getState();assert.equal(s.tawaf,7);assert.equal(s.sai,2);assert.equal(s.stage,4);assert.equal(s.running,false);assert.equal(s.paused,true);assert.ok(Math.hypot(s.position[0],s.position[2])>=47);assert.deepEqual(s.route[0],s.position);assert.equal(s.routeIds.at(-1),pois.find(p=>p.id==='upper-prayer')!.nodeId)})
test('legacy migration uses the actual user region when a different region was being viewed',async()=>{reset();memory.set(STORAGE_KEY,JSON.stringify({version:1,state:{position:[395,0,25],userFloor:0,floor:1,region:'haram',nodeId:'mina-camp',destination:'mina-toilets',route:[[395,0,25],[445,0,55]],routeIds:['mina-camp','mina-east'],progress:.1,tawaf:5,stage:3}}));await useMap.persist.rehydrate();const s=useMap.getState();assert.equal(s.tawaf,5);assert.equal(s.nodeId,'mina-camp');assert.deepEqual(s.position,[395,0,25]);assert.equal(s.destination,'mina-toilets');assert.equal(s.paused,true)})

test('bridge reports the viewed building and region-specific floor elevation',async()=>{Object.defineProperty(globalThis,'window',{value:{},configurable:true});const {mapBridge}=await import('./bridge');reset();useMap.getState().setRegion('towers');useMap.getState().setFloor(1);assert.equal(mapBridge.getCurrentFloor().y,16);assert.equal(mapBridge.getCurrentFloor().building,'towers');useMap.getState().setRegion('haram');useMap.getState().setFloor(9);assert.equal(mapBridge.getCurrentFloor().building,'masaa');assert.match(mapBridge.getCurrentFloor().name,/المسعى/);useMap.getState().setRegion('mina');assert.equal(mapBridge.getCurrentFloor().short,'G')})
