import { useLayoutEffect, useMemo, useRef, useEffect, memo } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { OrbitControls, Html } from '@react-three/drei'
import * as THREE from 'three'
import type { OrbitControls as OrbitImpl } from 'three-stdlib'
import {edges,nodes,pointAlong,pathLength} from './navigation'

export type Vec3 = [number, number, number]
export type CameraRequest = { id: number; target: Vec3; zoom?: number; reset?: boolean }
export type ScenePOI = { id:string; name:string; position:Vec3; color:string; symbol:string }
export interface SceneProps { floor:number; user:Vec3; direction:number; pois:ScenePOI[]; selected:string|null; route:Vec3[]; camera:CameraRequest; running:boolean; follow:boolean; routeProgress:number; crowd:boolean; onManual:()=>void; picking:boolean; onPick:(p:Vec3)=>void; onSelect:(id:string)=>void; onReady:()=>void }
const ivory='#ede9df', stone='#d6cec0', gold='#aa9467'
function Box({position,size,color=ivory,...rest}:{position:Vec3;size:Vec3;color?:string;rotation?:Vec3}) {return <mesh position={position} {...rest} castShadow receiveShadow><boxGeometry args={size}/><meshStandardMaterial color={color} roughness={.86}/></mesh>}
function Ring({inner,outer,y,color='#ddd5c5'}:{inner:number;outer:number;y:number;color?:string}){return <mesh rotation={[-Math.PI/2,0,0]} position={[0,y,0]} receiveShadow><ringGeometry args={[inner,outer,96]}/><meshStandardMaterial color={color} side={THREE.DoubleSide}/></mesh>}
function Arcade({level}:{level:number}){
 const pillars=useRef<THREE.InstancedMesh>(null!), caps=useRef<THREE.InstancedMesh>(null!), arches=useRef<THREE.InstancedMesh>(null!)
 const positions=useMemo(()=>Array.from({length:96},(_,i)=>{const a=i/96*Math.PI*2;return {x:Math.cos(a)*43,z:Math.sin(a)*43,a}}),[])
 useLayoutEffect(()=>{const o=new THREE.Object3D();positions.forEach(({x,z,a},i)=>{o.position.set(x,level+3,z);o.scale.set(1,1,1);o.rotation.set(0,0,0);o.updateMatrix();pillars.current.setMatrixAt(i,o.matrix);o.position.y=level+5.1;o.updateMatrix();caps.current.setMatrixAt(i,o.matrix);const mid=a+Math.PI/96;o.position.set(Math.cos(mid)*43,level+4.6,Math.sin(mid)*43);o.rotation.set(0,-mid,0);o.updateMatrix();arches.current.setMatrixAt(i,o.matrix)});[pillars,caps,arches].forEach(r=>r.current.instanceMatrix.needsUpdate=true)},[positions,level])
 return <><instancedMesh ref={pillars} args={[undefined,undefined,96]} castShadow><cylinderGeometry args={[.38,.5,5.2,8]}/><meshStandardMaterial color="#e9e3d6"/></instancedMesh><instancedMesh ref={caps} args={[undefined,undefined,96]}><boxGeometry args={[1.15,.5,1.15]}/><meshStandardMaterial color={stone}/></instancedMesh><instancedMesh ref={arches} args={[undefined,undefined,96]} castShadow><torusGeometry args={[1.37,.23,6,12,Math.PI]}/><meshStandardMaterial color={stone}/></instancedMesh></>
}
function FloorPlate({y}:{y:number}) {
 const geometry=useMemo(()=>{const s=new THREE.Shape();for(let i=0;i<8;i++){const a=i/8*Math.PI*2+Math.PI/8;const p=[Math.cos(a)*61,Math.sin(a)*61];i?s.lineTo(p[0],p[1]):s.moveTo(p[0],p[1])}s.closePath();const hole=new THREE.Path();hole.absarc(0,0,41,0,Math.PI*2,true);s.holes.push(hole);const g=new THREE.ExtrudeGeometry(s,{depth:1,bevelEnabled:false,curveSegments:64});g.rotateX(-Math.PI/2);return g},[])
 return <mesh geometry={geometry} position={[0,y,0]} castShadow receiveShadow><meshStandardMaterial color={ivory}/></mesh>
}
function Minaret({x,z}:{x:number;z:number}){return <group position={[x,0,z]}><Box position={[0,3,0]} size={[5,6,5]} color={stone}/><mesh position={[0,15,0]} castShadow><cylinderGeometry args={[1.3,1.8,22,12]}/><meshStandardMaterial color={ivory}/></mesh>{[10,23,28].map(y=><group key={y}><mesh position={[0,y,0]} castShadow><cylinderGeometry args={[2.3,2.3,.8,12]}/><meshStandardMaterial color={y===23?'#50766b':stone}/></mesh></group>)}<mesh position={[0,26,0]} castShadow><cylinderGeometry args={[.75,1.1,5,12]}/><meshStandardMaterial color={ivory}/></mesh><mesh position={[0,30,0]}><coneGeometry args={[1.05,3.2,12]}/><meshStandardMaterial color="#54796b"/></mesh><mesh position={[0,32.4,0]}><sphereGeometry args={[.4,8,8]}/><meshStandardMaterial color={gold}/></mesh></group>}
function Expansion(){
 const blocks=useMemo(()=>Array.from({length:5},(_,i)=>Array.from({length:3},(_,j)=>[-82+j*13,8,-39+i*19] as Vec3)).flat(),[])
 return <group><Box position={[-75,3,0]} size={[48,6,104]} color={stone}/><Box position={[-75,6.5,0]} size={[49,1,105]}/>{blocks.map((p,i)=><group key={i}><Box position={p} size={[10,3,15]} color="#e3ddcf"/><Box position={[p[0],9.6,p[2]]} size={[7,.2,11]} color="#9eaa9f"/>{[-5,5].map(d=><Box key={d} position={[p[0]+d,10.1,p[2]]} size={[.6,1,15]}/>)}</group>)}<Box position={[-102,4,0]} size={[5,8,75]}/>{Array.from({length:17},(_,i)=><Box key={i} position={[-104.6,3.8,-35+i*4.4]} size={[.2,4,2.4]} color="#818d83"/>)}</group>
}
const Architecture=memo(function Architecture({floor}:{floor:number}){
 return <group><mesh position={[0,-1.4,0]} receiveShadow><boxGeometry args={[233,2,210]}/><meshStandardMaterial color="#e5e4de"/></mesh><Box position={[0,-.25,0]} size={[122,.7,125]} color="#f1efe8"/><mesh rotation={[-Math.PI/2,0,0]} position={[0,.16,0]} receiveShadow><circleGeometry args={[41.5,96]}/><meshStandardMaterial color="#faf9f3"/></mesh>{[10,14,18,22,26,30,34,38,41].map(r=><Ring key={r} inner={r} outer={r+.12} y={.21}/>)}
 <Expansion/>
 {[0,1,2].map(f=><group key={f} name={`floor-${f}`} visible={f===0||floor===f} userData={{floor:f}}><FloorPlate y={f*9-.85}/><Arcade level={f*9}/>{Array.from({length:8},(_,i)=>{const a=i*Math.PI/4;return <group key={i} rotation={[0,-a,0]}><Box position={[55,f*9+3,0]} size={[3,6,39]} color={stone}/><Box position={[55,f*9+6.2,0]} size={[5,.8,42]}/>{Array.from({length:9},(_,j)=><Box key={j} position={[56.6,f*9+3,-16+j*4]} size={[.18,3,2.2]} color="#9a9f91"/>)}</group>})}</group>)}
 <group name="floor-3" visible={floor===0||floor===3} userData={{floor:3}}><Box position={[71,2,0]} size={[20,4,151]} color="#dbd6c8"/><Box position={[71,4.2,0]} size={[19,.4,148]} color="#f5f1e7"/><Box position={[71,4.5,0]} size={[.25,.2,138]} color="#afc0b3"/>{[-10,10].map(d=><group key={d}><Box position={[71+d,7,0]} size={[1,6,d===-10?88:151]}/>{Array.from({length:26},(_,i)=><Box key={i} position={[71+d,7,-70+i*5.5]} size={[1.15,5,.65]} color={stone}/>)}</group>)}{[-65,65].map(z=><mesh key={z} position={[71,5,z]} scale={[4,1.5,4]}><icosahedronGeometry args={[1,1]}/><meshStandardMaterial color="#acac94"/></mesh>)}</group>
 <group rotation={[0,.2,0]}><Box position={[0,4.6,0]} size={[9,9,10]} color="#252926"/><Box position={[0,7.1,0]} size={[9.14,.95,10.14]} color="#bba064"/><Box position={[0,.5,0]} size={[10,1,11]} color="#b5a58c"/><Box position={[4.56,4.2,1.8]} size={[.15,3,1.8]} color="#b7a16d"/><Box position={[0,9.17,0]} size={[9.3,.35,10.3]} color="#343631"/></group>
 <mesh rotation={[-Math.PI/2,0,0]} position={[-7,.8,-6]}><torusGeometry args={[4,.5,8,32,Math.PI*1.2]}/><meshStandardMaterial color={stone}/></mesh>
 <group position={[14,0,5]}><Box position={[0,1.5,0]} size={[2.2,3,2.2]} color={gold}/><mesh position={[0,3.7,0]}><sphereGeometry args={[1.5,12,8,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color={gold}/></mesh></group><Box position={[26,.18,9.3]} size={[7,.13,6]} color="#c3d2b8"/>
 {[[44,44],[-44,44],[44,-44],[-44,-44],[-96,-49],[-96,49]].map(([x,z])=><Minaret key={`${x},${z}`} x={x} z={z}/>)}
 {[0,1].map(f=><group key={f} visible={floor===f||floor===f+1}>{Array.from({length:12},(_,i)=><Box key={i} position={[48,f*9+i*.75,14+i*.65]} size={[4,.75,1]} color="#b8b9aa"/>) }<Box position={[-48,f*9+4,15]} size={[4,8,4]} color="#91aaa2"/><Box position={[48,f*9+4,-17]} size={[3,1,12]} rotation={[-.65,0,0]} color="#7d9189"/></group>)}
 <Box position={[0,.6,54]} size={[9,1.2,10]} color="#cac3b3"/><Box position={[0,.6,-54]} size={[9,1.2,10]} color="#cac3b3"/>
 </group>
})

function CameraRig({request,follow,user,direction,onManual}:{request:CameraRequest;follow:boolean;user:Vec3;direction:number;onManual:()=>void}){
 const ref=useRef<OrbitImpl>(null!);const {camera,size}=useThree();const goal=useRef<{target:THREE.Vector3;zoom:number;position:THREE.Vector3}|null>(null);const dragging=useRef(false)
 const baseZoom=Math.min(size.width/235,size.height/195)
 useEffect(()=>{const handler=(event:Event)=>{if(!ref.current)return;const action=(event as CustomEvent<string>).detail;const c=camera as THREE.OrthographicCamera;goal.current={target:ref.current.target.clone(),position:camera.position.clone(),zoom:THREE.MathUtils.clamp(c.zoom*(action==='zoom-in'?1.3:1/1.3),baseZoom*.6,baseZoom*5)}};window.addEventListener('sakina-camera',handler);return()=>window.removeEventListener('sakina-camera',handler)},[camera,baseZoom])
 useEffect(()=>{const t=new THREE.Vector3(...request.target);goal.current={target:t,zoom:request.zoom?baseZoom*request.zoom:baseZoom,position:t.clone().add(new THREE.Vector3(130,175,180))}},[request,baseZoom])
 useFrame((_,dt)=>{if(!ref.current)return;const c=camera as THREE.OrthographicCamera;if(follow){const t=new THREE.Vector3(...user);const k=1-Math.exp(-dt*3);ref.current.target.lerp(t,k);camera.position.lerp(t.clone().add(new THREE.Vector3(Math.sin(direction)*80,100,Math.cos(direction)*80)),k);c.zoom=THREE.MathUtils.lerp(c.zoom,baseZoom*2.8,k);c.updateProjectionMatrix();goal.current=null}if(goal.current){const g=goal.current,k=1-Math.exp(-dt*5);ref.current.target.lerp(g.target,k);camera.position.lerp(g.position,k);c.zoom=THREE.MathUtils.lerp(c.zoom,g.zoom,k);c.updateProjectionMatrix();if(camera.position.distanceTo(g.position)<.03&&Math.abs(c.zoom-g.zoom)<.003)goal.current=null}if(!dragging.current){const t=ref.current.target;const bounded=t.clone().clamp(new THREE.Vector3(-105,0,-85),new THREE.Vector3(85,25,85));camera.position.add(bounded.clone().sub(t));t.copy(bounded)}})
 return <OrbitControls ref={ref} makeDefault enableDamping minPolarAngle={.2} maxPolarAngle={Math.PI/2.65} minAzimuthAngle={-Math.PI*.65} maxAzimuthAngle={Math.PI*.65} minZoom={baseZoom*.6} maxZoom={baseZoom*5} maxDistance={500} onStart={()=>{goal.current=null;dragging.current=true;onManual()}} onEnd={()=>{dragging.current=false}} touches={{ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN}}/>
}
class WalkingCurve extends THREE.Curve<THREE.Vector3>{constructor(public points:Vec3[]){super()}getPoint(t:number,target=new THREE.Vector3()){return target.fromArray(pointAlong(this.points,t).position).add(new THREE.Vector3(0,.8,0))}}
function Route({points,progress}:{points:Vec3[];progress:number}){
 const curve=useMemo(()=>new WalkingCurve(points),[points]);const segments=Math.max(64,points.length*16);const geo=useMemo(()=>new THREE.TubeGeometry(curve,segments,.85,6,false),[curve,segments]);const dots=useRef<THREE.InstancedMesh>(null!);const obj=useMemo(()=>new THREE.Object3D(),[]);const start=pointAlong(points,progress).position
 useFrame(({clock})=>{geo.setDrawRange(Math.floor(progress*segments)*36,Math.max(0,(segments-Math.floor(progress*segments))*36));if(!dots.current)return;for(let i=0;i<12;i++){obj.position.copy(curve.getPoint(progress+(1-progress)*((clock.elapsedTime*.09+i/12)%1)));obj.position.y+=.65;obj.updateMatrix();dots.current.setMatrixAt(i,obj.matrix)}dots.current.instanceMatrix.needsUpdate=true})
 useEffect(()=>()=>geo.dispose(),[geo])
 return <group name="navigation-route"><mesh geometry={geo} renderOrder={2}><meshStandardMaterial color="#128c83" emissive="#198777" emissiveIntensity={.25}/></mesh><instancedMesh ref={dots} args={[undefined,undefined,12]}><sphereGeometry args={[.42,8,6]}/><meshBasicMaterial color="#e4fff2"/></instancedMesh>{[start,points[points.length-1]].map((p,i)=><mesh key={i} position={[p[0],p[1]+.6,p[2]]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[1.2,2.4,32]}/><meshBasicMaterial color={i?'#176b5e':'#3989d4'}/></mesh>)}</group>
}
function Corridors({floor,crowd}:{floor:number;crowd:boolean}){
 const geometries=useMemo(()=>edges.filter(e=>{const a=nodes.find(n=>n.id===e.from)!,b=nodes.find(n=>n.id===e.to)!;return e.kind!=='elevator'&&e.kind!=='stairs'&&e.kind!=='escalator'&&(a.floor===floor||b.floor===floor)}).map(e=>{const a=new THREE.Vector3(...nodes.find(n=>n.id===e.from)!.position),b=new THREE.Vector3(...nodes.find(n=>n.id===e.to)!.position);const mid=a.clone().add(b).multiplyScalar(.5);mid.y+=.3;const g=new THREE.BoxGeometry(5.2,.16,a.distanceTo(b));const rotation=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,1),b.clone().sub(a).normalize());g.applyQuaternion(rotation);return {id:e.id,position:mid,geometry:g}}),[floor])
 useEffect(()=>()=>geometries.forEach(g=>g.geometry.dispose()),[geometries]);return <group name="walkable-corridors">{geometries.map(g=><mesh key={g.id} geometry={g.geometry} position={g.position} receiveShadow><meshStandardMaterial color={crowd&&g.id==='main-passage'?'#dca273':'#d3d7c8'} roughness={.9}/></mesh>)}</group>
}
function UserMarker({position,direction}:{position:Vec3;direction:number}){
 const group=useRef<THREE.Group>(null!),pulse=useRef<THREE.Mesh>(null!)
 useFrame(({clock},dt)=>{group.current.position.lerp(new THREE.Vector3(position[0],position[1]+1,position[2]),1-Math.exp(-dt*12));pulse.current.scale.setScalar(1+(Math.sin(clock.elapsedTime*2)+1)*.35)})
 return <group ref={group} position={position} name="user-location"><Html position={[0,5,0]} center zIndexRange={[22,21]}><div className="user-label"><b>أنت هنا</b><span>افتراضي</span></div></Html><mesh ref={pulse} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[1.8,3,40]}/><meshBasicMaterial color="#4196ee" transparent opacity={.2} depthWrite={false}/></mesh><mesh><sphereGeometry args={[1.15,20,12]}/><meshStandardMaterial color="#388bf4" emissive="#176acc" emissiveIntensity={.5}/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.2,0]}><ringGeometry args={[1.1,1.5,32]}/><meshBasicMaterial color="white"/></mesh><group rotation={[0,direction,0]}><mesh position={[0,.15,-2.1]} rotation={[-Math.PI/2,0,0]}><coneGeometry args={[.8,1.7,3]}/><meshBasicMaterial color="#398bf1"/></mesh></group></group>
}
function Contents(props:SceneProps){const {gl}=useThree();useEffect(()=>{gl.domElement.dataset.engine='three-webgl';props.onReady()},[gl]);return <><color attach="background" args={['#ecece6']}/><ambientLight intensity={1.6}/><directionalLight position={[-60,130,70]} intensity={2.4} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-145} shadow-camera-right={145} shadow-camera-top={145} shadow-camera-bottom={-145} shadow-bias={-.001}/><Architecture floor={props.floor}/><Corridors floor={props.floor} crowd={props.crowd}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,props.floor===3?4.55:props.floor*9+.35,0]} visible={props.picking} onClick={e=>{e.stopPropagation();props.onPick([e.point.x,e.point.y,e.point.z])}}><planeGeometry args={[230,200]}/><meshBasicMaterial color="#62aa96" transparent opacity={.12} depthWrite={false}/></mesh>{props.route.length>1&&pathLength(props.route)>.01&&<Route points={props.route} progress={props.routeProgress}/>}<UserMarker position={props.user} direction={props.direction}/>{props.pois.map(p=><Html key={p.id} position={[p.position[0],p.position[1]+4,p.position[2]]} center zIndexRange={[20,0]}><button className={`poi ${props.selected===p.id?'selected':''}`} style={{'--poi-color':p.color} as React.CSSProperties} onClick={()=>props.onSelect(p.id)} aria-label={p.name}><span>{p.symbol}</span><b>{p.name}</b></button></Html>)}<CameraRig request={props.camera} follow={props.follow&&props.running} user={props.user} direction={props.direction} onManual={props.onManual}/></>}
const sceneShadows=window.innerWidth>600
const sceneCamera={position:[130,175,180] as Vec3,zoom:3,near:.1,far:1000}
const sceneGl={antialias:true,powerPreference:'high-performance' as const}
export default function Scene(props:SceneProps){return <Canvas orthographic shadows={sceneShadows} dpr={[1,1.6]} camera={sceneCamera} gl={sceneGl}><Contents {...props}/></Canvas>}
