import {floorElevation,buildingFor,haramLevels} from './levels'
import {regionAt,regionConfig,regions,closureByRegion} from './geography'
import type {RegionView,RegionId} from './geography'
import {create} from 'zustand'
import {persist} from 'zustand/middleware'
import {floors,nodes,pois,stages,nearestNode,shortestPath,pathLength,remainingPath,tawafPath,distance} from './navigation'
import type {Category,Vec3} from './navigation'
import {MockLocationProvider} from './location'
import type {LocationProvider} from './location'
import {t, poiName} from './i18n/index'
import type {Lang} from './i18n/index'
let provider:LocationProvider=new MockLocationProvider()
export function setLocationProvider(next:LocationProvider){provider=next}
export const STORAGE_KEY='sakina.journey.v1'
interface MapState {
 region:RegionView;lang:Lang;floor:number;userFloor:number;position:Vec3;nodeId:string;direction:number;destination:string|null;selected:string|null;route:Vec3[];routeIds:string[];progress:number;running:boolean;paused:boolean;stoppedAt:string|null;stage:number;started:boolean;completed:number[];arrived:string[];tawaf:number;sai:number;ritual:'tawaf'|'sai'|null;accessible:boolean;closed:string[];demo:'off'|'first'|'saved'|'resumed'|'arrived'|'sai';toast:string;storageError:boolean;preferQuiet:boolean;follow:boolean;lostLandmark:string|null;camera:{id:number;target:Vec3;zoom?:number};
 setRegion:(region:RegionView)=>void;startRegionDemo:(region:RegionId)=>void;setLang:(lang:Lang)=>void;toggleQuiet:()=>void;toggleFollow:()=>void;lost:()=>void;finishTawaf:()=>void;setFloor:(id:number)=>void;focus:(target:Vec3,zoom?:number)=>void;select:(id:string)=>void;navigate:(id:string)=>boolean;frameRoute:()=>void;moveTo:(p:Vec3,f?:number)=>void;nearest:(category:Category)=>string|null;toggleAccessible:()=>void;toggleClosure:()=>void;tick:(dt:number)=>void;pause:()=>void;resume:()=>void;simulate:()=>void;confirmArrival:(id:string)=>boolean;completeStage:()=>void;startRitual:(type:'tawaf'|'sai')=>void;completeLap:()=>void;undoLap:()=>void;resetLaps:()=>void;resetJourney:()=>void;startDemo:()=>void;setToast:(text:string)=>void;startJourney:()=>void
}
const storage={getItem:(name:string)=>{try{return localStorage.getItem(name)}catch{return null}},setItem:(name:string,value:string)=>{try{localStorage.setItem(name,value)}catch{queueMicrotask(()=>{if(!useMap.getState().storageError)useMap.setState({storageError:true})})}},removeItem:(name:string)=>{try{localStorage.removeItem(name)}catch{/* Storage may be unavailable. */}}}
export const useMap=create<MapState>()(persist<MapState, [], [], Partial<MapState>>((set,get)=>({
 region:'haram',lang:'ar',floor:0,userFloor:0,position:[0,0,54],nodeId:'f0-south',direction:0,destination:null,selected:null,route:[],routeIds:[],progress:0,running:false,paused:false,stoppedAt:null,stage:0,started:false,completed:[],arrived:[],tawaf:0,sai:0,ritual:null,accessible:false,closed:[],demo:'off',toast:'',storageError:false,preferQuiet:false,follow:false,lostLandmark:null,camera:{id:0,target:[-5,0,0],zoom:1.9},
 // Stage 0 ("enter through the gate") isn't a real walk the demo can
 // simulate meaningfully - starting the journey assumes that part
 // already happened and begins actual navigation from stage 1 (heading
 // to the mataf) instead, same as completeStage()'s own advance-past-a-
 // stage logic.
 startJourney:()=>{set({started:true,completed:[0],arrived:['gate-fahd'],stage:1});get().navigate(stages[1].poi);set({running:true,follow:true})},
 setRegion:region=>{if(region!=='overview'&&!regions.some(r=>r.id===region))return;const f=region==='overview'?0:regionConfig(region).floors.includes(get().floor)?get().floor:0;set({region,floor:f,selected:null,follow:false});if(region==='overview')get().focus([450,10,-25],.24);else{const c=regionConfig(region);get().focus([c.center[0],c.center[1]+floorElevation(region,f),c.center[2]],c.zoom)}},
 startRegionDemo:region=>{const c=regionConfig(region),n=nodes.find(n=>n.id===c.entry)!;set({position:n.position,nodeId:n.id,userFloor:n.floor,floor:n.floor,region,running:false,ritual:null,demo:'off',paused:false,lostLandmark:null});get().navigate(c.destination);set({running:true,follow:true})},
 setLang:lang=>set({lang}),
 setToast:toast=>set({toast}),focus:(target,zoom=1.65)=>set(s=>({camera:{id:s.camera.id+1,target,zoom}})),
 setFloor:floor=>{if(!floors.some(f=>f.id===floor))return;const region=get().region==='overview'?regionAt(get().position):get().region as RegionId;const c=regionConfig(region);if(!c.floors.includes(floor))return;set({floor,region,selected:null,follow:false});get().focus(region==='haram'&&buildingFor(floor)==='masaa'?[71,floorElevation(region,floor),0]:[c.center[0],floorElevation(region,floor),c.center[2]],c.zoom)},
 select:id=>{const p=pois.find(p=>p.id===id);if(!p)return;set({selected:id,floor:p.floor,region:p.region,follow:false});get().focus(p.position,1.55)},
 navigate:id=>{const p=pois.find(p=>p.id===id);if(!p){set({toast:t('toast.location_not_found',get().lang)});return false}const s=get(),start=nearestNode(s.position,s.userFloor);const result=shortestPath(start.id,p.nodeId,s.accessible,s.closed,s.preferQuiet);if(!result){set({toast:t('toast.no_route_available',get().lang)});return false}const points=distance(s.position,result.points[0])>.01?[s.position,...result.points]:result.points;set({route:points.length===1?[s.position,[...points[0]]]:points,routeIds:result.ids,destination:id,selected:null,progress:0,ritual:null,running:false,follow:false,paused:false,stoppedAt:null,floor:s.userFloor,toast:t('toast.route_ready',get().lang)});get().frameRoute();return true},
 frameRoute:()=>{const r=get().route;if(!r.length)return;const rs=new Set(get().routeIds.map(id=>nodes.find(n=>n.id===id)!.region));set({follow:false,region:rs.size>1?'overview':regionAt(r[0])});const bounds=r.reduce((a,p)=>({min:a.min.map((v,i)=>Math.min(v,p[i])) as Vec3,max:a.max.map((v,i)=>Math.max(v,p[i])) as Vec3}),{min:[...r[0]] as Vec3,max:[...r[0]] as Vec3});const center=bounds.min.map((v,i)=>(v+bounds.max[i])/2) as Vec3;const extent=Math.max(bounds.max[0]-bounds.min[0],bounds.max[2]-bounds.min[2],40);get().focus(center,Math.min(2.1,140/extent))},
 moveTo:(p,f=get().floor)=>{const n=nearestNode(p,f);set({position:n.position,userFloor:n.floor,floor:n.floor,region:n.region,nodeId:n.id,progress:0,running:false,ritual:null,demo:'off'});if(get().destination){get().navigate(get().destination!);set({toast:t('toast.location_updated',get().lang)})}else set({toast:t('toast.demo_location_set',get().lang)})},
 nearest:category=>{const s=get();const candidates=pois.filter(p=>p.category===category).map(p=>({p,r:shortestPath(s.nodeId,p.nodeId,s.accessible,s.closed,s.preferQuiet)})).filter(x=>x.r).sort((a,b)=>a.r!.meters-b.r!.meters);if(!candidates[0]){set({toast:t('toast.no_accessible_service',get().lang)});return null}get().select(candidates[0].p.id);return candidates[0].p.id},
 toggleQuiet:()=>{set(s=>({preferQuiet:!s.preferQuiet}));if(get().destination)get().navigate(get().destination!);set({toast:t(get().preferQuiet?'toast.quiet_on':'toast.quiet_off',get().lang)})},
 toggleFollow:()=>set(s=>({follow:!s.follow})),
 lost:()=>{const s=get();const known=pois.filter(p=>['gate','ritual','meeting'].includes(p.category)&&p.floor===s.userFloor&&p.id!=='kaaba');const closest=known.map(p=>({p,r:shortestPath(s.nodeId,p.nodeId,s.accessible,s.closed)})).filter(x=>x.r).sort((a,b)=>a.r!.meters-b.r!.meters)[0];if(closest){set({lostLandmark:closest.p.id,selected:null,floor:s.userFloor,region:regionAt(s.position),follow:false,toast:t('toast.lost_found_landmark',s.lang,{name:poiName(closest.p.id,s.lang)})});get().focus(s.position,2.4)}},
 finishTawaf:()=>{const route=tawafPath();set({tawaf:7,stage:4,ritual:null,completed:[...new Set([...get().completed,3])],position:route.at(-1)!,nodeId:'f0-r0',userFloor:0,floor:0,demo:'off'});get().navigate('prayer');set({running:true,follow:true,toast:t('toast.tawaf_finished',get().lang)})},
 toggleAccessible:()=>{set(s=>({accessible:!s.accessible}));if(get().destination)get().navigate(get().destination!);set({toast:t(get().accessible?'toast.accessible_on':'toast.accessible_off',get().lang)})},
 toggleClosure:()=>{const region=get().region==='overview'?regionAt(get().position):get().region as RegionId;const id=closureByRegion[region];if(!id)return;set(s=>({closed:s.closed.includes(id)?s.closed.filter(c=>c!==id):[...s.closed,id]}));if(get().destination)get().navigate(get().destination!);set({toast:t(get().closed.length?'toast.closure_on':'toast.closure_off',get().lang)})},
 tick:dt=>{const s=get();if(!s.running||s.route.length<2)return;const total=pathLength(s.route);const speed=s.demo!=='off'?10:s.ritual?15:total>180?Math.min(50,total/30):5;const sample=provider.advance(s.route,s.progress,Math.min(dt,.3),speed);let userFloor=s.userFloor;if(s.routeIds.length){const nearest=nodes.filter(n=>s.routeIds.includes(n.id)).sort((a,b)=>distance(a.position,sample.position)-distance(b.position,sample.position))[0];if(nearest)userFloor=nearest.floor}else if(s.ritual)userFloor=s.ritual==='sai'?3:0;const n=nearestNode(sample.position,userFloor);set({position:sample.position,direction:sample.direction,progress:sample.progress,userFloor,nodeId:n.id,floor:s.follow?userFloor:s.floor,region:s.follow?n.region:s.region});
 if(s.demo==='first'&&sample.progress>=.5){set({demo:'saved',toast:t('toast.demo_saved',s.lang)});get().pause();return}
 if(sample.progress>=1){set({running:false,toast:t(s.ritual?'toast.sim_arrived_lap':'toast.sim_arrived_destination',s.lang)});if(s.demo==='resumed'){set({demo:'arrived'});get().focus([71,4.5,0],1.2)}}
 },
 pause:()=>set({running:false,follow:false,paused:true,stoppedAt:new Date().toISOString(),toast:t('toast.paused_saved',get().lang)}),
 resume:()=>{const s=get();set({paused:false,follow:true,running:s.route.length>1,stoppedAt:null,floor:s.userFloor,region:regionAt(s.position),demo:s.demo==='saved'?'resumed':s.demo,toast:t('toast.welcome_back',s.lang)});get().focus(s.position,1.8)},
 simulate:()=>{if(get().route.length<2){set({toast:t('toast.choose_destination_first',get().lang)});return}if(get().progress>=1){set({toast:t('toast.route_finished',get().lang)});return}set(s=>({running:!s.running,follow:!s.running,paused:false}))},
 confirmArrival:id=>{const p=pois.find(p=>p.id===id);if(!p)return false;const s=get();if(s.userFloor!==p.floor||distance(s.position,nodes.find(n=>n.id===p.nodeId)!.position)>10){set({toast:t('toast.sim_not_arrived',s.lang)});return false}set({arrived:[...new Set([...s.arrived,id])],toast:t('toast.arrival_confirmed',s.lang)});if(s.demo==='arrived'&&id==='safa'){set({stage:7,completed:[...new Set([...s.completed,6])],demo:'sai'});get().startRitual('sai')}return true},
 completeStage:()=>{const s=get();if(s.stage===3&&s.tawaf<7||s.stage===7&&s.sai<7){set({toast:t('toast.complete_seven_first',s.lang)});return}if(s.stage<9&&!s.arrived.includes(stages[s.stage].poi)){set({toast:t('toast.confirm_arrival_first',s.lang)});return}set({completed:[...new Set([...s.completed,s.stage])],stage:Math.min(9,s.stage+1),toast:t(s.stage===9?'toast.umrah_complete':'toast.stage_confirmed',s.lang)});if(s.stage<9){const next=s.stage+1;if(next===3||next===7)get().startRitual(next===3?'tawaf':'sai');else{get().navigate(stages[next].poi);set({running:true,follow:true})}}},
 startRitual:type=>{const s=get();const count=type==='tawaf'?s.tawaf:s.sai;if(count>=7){set({toast:t('toast.seven_laps_done',s.lang)});return}const route=type==='tawaf'?tawafPath():count%2===0?[[71,4.5,65],[71,4.5,-65]] as Vec3[]:[[71,4.5,-65],[71,4.5,65]] as Vec3[];const f=type==='tawaf'?0:3;set({ritual:type,route,routeIds:[],position:route[0],nodeId:type==='tawaf'?'f0-r0':count%2===0?'safa':'marwa',userFloor:f,floor:f,region:'haram',stage:type==='tawaf'?3:7,destination:type==='tawaf'?'tawaf-start':count%2===0?'marwa':'safa',progress:0,running:true,follow:true,paused:false,toast:t('toast.ritual_note',s.lang)});get().focus(type==='tawaf'?[0,0,0]:[71,4.5,0],type==='tawaf'?2:1.15)},
 completeLap:()=>{const s=get();if(!s.ritual)return;const type=s.ritual;set({position:s.route.at(-1)!,nodeId:type==='tawaf'?'f0-r0':s.sai%2===0?'marwa':'safa'});const n=Math.min(7,(type==='tawaf'?s.tawaf:s.sai)+1);set(type==='tawaf'?{tawaf:n}:{sai:n});if(n===7){const stage=type==='tawaf'?3:7;set({running:false,ritual:null,stage:stage+1,completed:[...new Set([...s.completed,stage])],toast:t('toast.lap_completed',s.lang),demo:'off'});get().navigate(type==='tawaf'?'prayer':'exit');set({running:true,follow:true})}else get().startRitual(type)},
 undoLap:()=>{const s=get();if(!s.ritual)return;if(s.ritual==='tawaf')set({tawaf:Math.max(0,s.tawaf-1)});else set({sai:Math.max(0,s.sai-1)});get().startRitual(s.ritual);set({running:false,toast:t('toast.lap_undone',s.lang)})},
 resetLaps:()=>{const s=get();if(!s.ritual)return;set(s.ritual==='tawaf'?{tawaf:0}:{sai:0});get().startRitual(s.ritual);set({running:false,toast:t('toast.laps_reset',s.lang)})},
 resetJourney:()=>{set({stage:0,started:false,completed:[],arrived:[],tawaf:0,sai:0,ritual:null,running:false,paused:false,stoppedAt:null,demo:'off',destination:null,route:[],routeIds:[],progress:0,position:[0,0,54],nodeId:'f0-south',userFloor:0,floor:0,region:'haram',toast:t('toast.journey_reset',get().lang)});get().focus([0,0,54],1.8)},
 startDemo:()=>{set({position:[48,0,22],nodeId:'f0-east',userFloor:0,floor:0,stage:6,completed:[],arrived:[],tawaf:0,sai:0,closed:[],demo:'first',paused:false,ritual:null});get().navigate('safa');set({running:true,follow:true,toast:t('toast.demo_intro',get().lang)});get().focus([48,0,22],1.7)}
}),{name:STORAGE_KEY,version:3,migrate:(saved)=>{const p=saved as Partial<MapState>;if(!p.position||!haramLevels.some(l=>l.id===p.userFloor))return{};const r=regionAt(p.position);const candidates=nodes.filter(n=>n.floor===p.userFloor&&n.region===r);const n=candidates.sort((a,b)=>distance(a.position,p.position!)-distance(b.position,p.position!))[0];if(!n)return{};if(p.ritual)return p;const dest=pois.find(d=>d.id===p.destination),route=dest?shortestPath(n.id,dest.nodeId,p.accessible,p.closed,p.preferQuiet):null;return{...p,position:n.position,nodeId:n.id,route:route?.points||[],routeIds:route?.ids||[],progress:0,paused:!!route}},storage:{getItem:name=>{const data=storage.getItem(name);if(!data)return null;try{return JSON.parse(data)}catch{return null}},setItem:(name,value)=>storage.setItem(name,JSON.stringify(value)),removeItem:storage.removeItem},partialize:s=>({region:s.region,lang:s.lang,floor:s.floor,userFloor:s.userFloor,position:s.position,nodeId:s.nodeId,direction:s.direction,destination:s.destination,route:s.route,routeIds:s.routeIds,progress:s.progress,stage:s.stage,started:s.started,completed:s.completed,arrived:s.arrived,tawaf:s.tawaf,sai:s.sai,ritual:s.ritual,paused:s.paused,stoppedAt:s.stoppedAt,accessible:s.accessible,preferQuiet:s.preferQuiet,closed:s.closed,demo:s.demo}),merge:(saved,current)=>{const p=saved as Partial<MapState>;if(!Array.isArray(p.position)||p.position.length!==3||!p.position.every(Number.isFinite))return current;return{...current,...p,region:p.region&&(['overview',...regions.map(r=>r.id)] as string[]).includes(p.region)?p.region:regionAt(p.position),running:false,paused:Boolean(p.route?.length||p.paused),camera:{id:1,target:p.route?.length?p.position:p.region==='overview'?[450,10,-25]:regionConfig(p.region||regionAt(p.position)).center,zoom:p.route?.length?1.5:p.region==='overview'?.24:regionConfig(p.region||regionAt(p.position)).zoom}}}}))
export const getRemainingMeters=()=>{const s=useMap.getState();return Math.round(pathLength(remainingPath(s.route,s.progress))*2.8)}
